// Curated, explicitly-named icon imports so bundlers can tree-shake unused
// icons out of the build. `import * as SimpleIcons from 'react-icons/si'`
// would pull in all ~3,400 Simple Icons (multi-MB) regardless of how many
// are actually used, so instead we hand-pick the technologies a portfolio
// is realistically going to list and fall back to a generic glyph for
// anything outside that set.
import {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiRedux,
  SiGraphql,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiPhp,
  SiLaravel,
  SiPython,
  SiDjango,
  SiFlask,
  SiRubyonrails,
  SiRuby,
  SiGo,
  SiRust,
  SiCplusplus,
  SiC,
  SiSharp,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiSqlite,
  SiRedis,
  SiFirebase,
  SiSupabase,
  SiDocker,
  SiKubernetes,
  SiVercel,
  SiNetlify,
  SiGit,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiJest,
  SiWebpack,
  SiVite,
  SiNpm,
  SiYarn,
  SiLinux,
  SiNginx,
  SiPostman,
  SiSocketdotio,
  SiThreedotjs,
  SiFlutter,
  SiKotlin,
  SiSwift,
  SiCodesandbox,
} from 'react-icons/si';
import { FaGithub, FaLinkedin, FaXTwitter, FaInstagram, FaJava } from 'react-icons/fa6';
import {
  Layers,
  MonitorSmartphone,
  Database,
  Mail,
  Phone,
  MapPin,
  Globe,
  Code2,
  Server,
  Palette,
  Zap,
  Sparkles,
  ArrowRight,
  ExternalLink,
} from 'lucide-react';

const TECH_ICON_MAP = {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3: SiCss,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiRedux,
  SiGraphql,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiPhp,
  SiLaravel,
  SiPython,
  SiDjango,
  SiFlask,
  SiRubyonrails,
  SiRuby,
  SiGo,
  SiRust,
  SiCplusplus,
  SiC,
  SiCsharp: SiSharp,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiSqlite,
  SiRedis,
  SiFirebase,
  SiSupabase,
  SiDocker,
  SiKubernetes,
  SiVercel,
  SiNetlify,
  SiGit,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiJest,
  SiWebpack,
  SiVite,
  SiNpm,
  SiYarn,
  SiLinux,
  SiNginx,
  SiPostman,
  SiSocketdotio,
  SiThreedotjs,
  SiFlutter,
  SiKotlin,
  SiSwift,
  SiJava: FaJava,
};

export function resolveTechIcon(name) {
  return TECH_ICON_MAP[name] || SiCodesandbox;
}

// Brand/social icons (GitHub, LinkedIn, X, Instagram) are resolved through
// Font Awesome's brand set, keyed by a short admin-friendly alias.
const SOCIAL_ICON_MAP = {
  Github: FaGithub,
  Linkedin: FaLinkedin,
  Twitter: FaXTwitter,
  Instagram: FaInstagram,
};

const LUCIDE_MAP = {
  Layers,
  MonitorSmartphone,
  Database,
  Mail,
  Phone,
  MapPin,
  Globe,
  Code2,
  Server,
  Palette,
  Zap,
  Sparkles,
  ArrowRight,
  ExternalLink,
};

export function resolveLucideIcon(name) {
  return SOCIAL_ICON_MAP[name] || LUCIDE_MAP[name] || Sparkles;
}
